typedef struct nodo_texto* texto;
texto nuevo_nodo_texto();
void recorrer_e_imprimir_texto(texto t, char* nombre_arch, char* version);
int contador_lineas(texto v);
void insertar(texto &t, int nmr_linea, char* linea_a_insert);
void eliminar_linea(texto &t, int nmr_linea, nodoV v);
void eliminar_texto(texto &t);
texto siguientelinea(texto t);
int numerolinea(texto t);
void linea(texto t,char * &s);
texto insertar_cambio_historial(nodoV v, int nmr_linea, char* linea_a_insert, int x);
